\documentclass{article}
\usepackage{float, hyperref}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{caption}
\usepackage{pgffor}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<options, echo=FALSE>>=
nClusters = 30
library(knitr)
opts_chunk$set(concordance=TRUE)
@

<<echo=FALSE,eval=TRUE>>=
library(rtracklayer)
library(Rsamtools)
library(grid)
library(GenomicAlignments)
library(ggplot2)
library(GGally)
library(edgeR)
library(stringr)
library(EDASeq)
library(dplyr)
library(matrixStats)
library(gridExtra)
library(reshape2)
library(scales)

plotName = "DR_DU"
outDir = "Clustering_DR_DU"
dir.create(paste(getwd(),"/",outDir,sep=""))
@

%\author{Lindsay Rutter}
\title{Cluster Analysis of Wasp DR DU}

\maketitle

<<echo=FALSE>>=
rm(list=ls())
load("All_wasp.rda")
countTableWasp = countTable
y <- DGEList(counts=countTableWasp)
@

<<echo=FALSE>>=
# Now try to threshold count number and normalize on the six samples
#L120 (157691, 12)
L120 = y[ , grepl( c("D") , colnames(y$counts))]

#L120 is (39886, 6)
# Make sure each gene has at least one count in at least half of the six samples
L120 <- L120[rowSums(L120$counts>1)>=ncol(L120)/2,]
# Now positive and negative
cpm.L120.new <- cpm(L120, TRUE, TRUE)
cpm.L120.norm <- betweenLaneNormalization(cpm.L120.new, which="full", round=FALSE)
L120 = cpm.L120.norm

RowSD = function(x) {
  sqrt(rowSums((x - rowMeans(x))^2)/(dim(x)[2] - 1))
}

L120t = L120
L120 = as.data.frame(L120t)
L120 = mutate(L120, mean = (DR.1+DR.2+DR.3+DR.4+DR.5+DR.6+DU.1+DU.2+DU.3+DU.4+DU.5+DU.6)/ncol(L120), stdev = RowSD(cbind(DR.1,DR.2,DR.3,DR.4,DR.5,DR.6,DU.1,DU.2,DU.3,DU.4,DU.5,DU.6)))
rownames(L120)=rownames(L120t)
# L120 = (39120, 8)

# The first quartile threshold of mean counts across the 5 samples
q1T = as.numeric(summary(L120$mean)["1st Qu."])
L120q1 = subset(L120,mean>q1T)
# The first quartile threshold of standard deviation across the 5 samples
q1Ts = as.numeric(summary(L120q1$stdev)["1st Qu."])
# L120q1 (22439, 14)
L120q1 = subset(L120q1,stdev>q1Ts)
# filt (17447, 14)
filt = subset(L120,mean<=q1T|stdev<=q1Ts)
# plotting purposes only
#ind = seq(1, nrow(L120), by=10)
#L120Plot=L120[ind, ]
@

<<echo=FALSE>>=
model = loess(mean ~ stdev, data=L120q1)
# L120q1 (9624, 14)
L120q1 = L120q1[which(sign(model$residuals) == 1),]

L120q1 = L120q1[,1:(ncol(L120q1)-2)]
L120q1s = t(apply(as.matrix(L120q1), 1, scale))
colnames(L120q1s)=colnames(L120q1)
colnames(L120q1)=colnames(L120q1) 
filt = filt[,1:(ncol(filt)-2)]
colnames(filt)=colnames(L120q1)
# filt (17447, 12)
filt = rbind(filt,L120q1[which(sign(model$residuals) == -1),])
# filt (30262, 12)
filts = t(apply(as.matrix(filt), 1, scale))
colnames(filts)=colnames(L120q1)
colnames(filt)=colnames(L120q1)
@

<<echo=FALSE>>=
# L120q1s (9809, 6)
dendo = L120q1s
rownames(dendo) = NULL
# Euclidean distance between rows of matrix
d = dist(as.matrix(dendo))
# Hierarchical clustering using ward.D linkage
hc = hclust(d, method="ward.D")
plotName = "DR_DU_Dendogram"
outDir = "Clustering_DR_DU"
jpeg(file = paste(getwd(), "/", outDir, "/", plotName, "_.jpg", sep=""))
plot(hc,main=plotName, xlab=NA, sub=NA)
invisible(dev.off())

scatmat(L120) # manually saved
scatmat(L120q1s) #error: "Error in if (ncol(dn) == 0) { : argument is of length zero"
@

%\begin{figure}[H]
%\centering
%<<echo=FALSE>>=
%plotName = "DR_DU"
%plot(hc,main=paste(plotName, "Dendogram"), xlab=NA, sub=NA)
%
%\end{figure}

%%%%%%%%%%%%%%%%%%%% PLOT CLUSTERS %%%%%%%%%%%%%%%%%%%%%

<<echo=FALSE,eval=TRUE,results='asis'>>=
getPCP <- function(nC){

plotName = "DR_DU"
outDir = "Clustering_DR_DU"

set.seed(1)
colList = scales::hue_pal()(nC+1)
k = cutree(hc, k=nC)
###########################
plot_clusters = lapply(1:nC, function(i){
  x = as.data.frame(L120q1s[which(k==i),])
  nGenes = nrow(x)
  x$cluster = "color"
  x$cluster2 = factor(x$cluster)
  xNames = rownames(x)
  write.table(xNames, file = paste(getwd(), "/", outDir, "/", plotName, "_", nC, "_", i, ".txt", sep=""), sep=",", row.names=FALSE, col.names=FALSE, quote=FALSE)  
  
  p = ggparcoord(x, columns=1:12, groupColumn=14, scale="globalminmax", alphaLines = 0.2) + xlab(paste("Cluster ", i, " (n=", format(nGenes, big.mark=",", scientific=FALSE), ")",sep="")) + ylab("Count") + theme(legend.position = "none", axis.title=element_text(size=12), axis.text=element_text(size=12), axis.text.x = element_text(angle = 90, hjust = 1)) + scale_colour_manual(values = c("color" = colList[i+1]))
  fileName = paste(getwd(), "/", outDir, "/", plotName, "_", nC, "_", i, ".jpg", sep="")
  jpeg(fileName)
  plot(p)
  invisible(dev.off())
  p
})
###########################
  filts = as.data.frame(filts)
  filts$cluster = "color"
  filts$cluster2 = factor(filts$cluster)
  nGenes = nrow(filts)
  plot_filtered = ggparcoord(filts, columns=1:12, groupColumn=14, scale="globalminmax", alphaLines = 0.01) + xlab(paste("Filtered (n=", format(nGenes, big.mark=",", scientific=FALSE), ")",sep="")) + ylab("Count") + theme(legend.position = "none", axis.title=element_text(size=12), axis.text=element_text(size=12), axis.text.x = element_text(angle = 90, hjust = 1)) + scale_colour_manual(values = c("color" = colList[1]))
###########################
  jpeg(file = paste(getwd(), "/", outDir, "/", plotName, "_", nC, ".jpg", sep=""), height = 200 * ceiling((nC+1)/3), width = min(200 * (nC+1), 800))
  # We allow up to 4 (now 3) plots in each column
  p = do.call("grid.arrange", c(append(plot_clusters, list(plot_filtered)), ncol=3)) #change from 4 to 3 ceiling(nC/3)
  invisible(dev.off())
}
@

<<echo=FALSE,eval=TRUE,results='asis'>>=
for (i in 2:30){
  getPCP(i)
}
@

\begin{center}
\foreach \i in {2,3,...,15} {
  \includegraphics[width=0.99\textwidth]{Clustering_DR_DU/DR_DU_\i}
  \captionof{figure}{Parallel coordinate plot of the normalized DR_DU read counts across \i\ clusters}
}
\end{center}

%%%%%%%%%%%%%%%%%%%%%%%%% PLOT SCATTERPLOTS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<echo=FALSE,eval=TRUE,results='asis'>>=
getPCP <- function(nC){

plotName = "DR_DU"
outDir = "Clustering_DR_DU"

set.seed(1)
colList = scales::hue_pal()(nC+1)
k = cutree(hc, k=nC)
###########################
plot_clusters = lapply(1:nC, function(i){
  x = as.data.frame(L120q1s[which(k==i),])
  nGenes = nrow(x)
  x$cluster = "color"
  x$cluster2 = factor(x$cluster)
  xNames = rownames(x)
  write.table(xNames, file = paste(getwd(), "/", outDir, "/", plotName, "_", nC, "_", i, ".txt", sep=""), sep=",", row.names=FALSE, col.names=FALSE, quote=FALSE)  
  p = ggparcoord(x, columns=1:12, groupColumn=14, scale="globalminmax", alphaLines = 0.2) + xlab(paste("Cluster ", i, " (n=", format(nGenes, big.mark=",", scientific=FALSE), ")",sep="")) + ylab("Count") + theme(legend.position = "none", axis.title=element_text(size=12), axis.text=element_text(size=12)) + scale_colour_manual(values = c("color" = colList[i+1]))
  fileName = paste(getwd(), "/", outDir, "/", plotName, "_", nC, "_", i, ".jpg", sep="")
  jpeg(fileName)
  plot(p)
  invisible(dev.off())
  p
})
}
@


\end{document}
